### ISSUE TITLE
info command crashes in 7.1.0

### ISSUE THREAD

**Issue by theRobinator** [bolinfest/plovr#129]
I just downloaded the 7.1.0 jar from the releases page. I'm running OSX 10.11 with Java 1.8.

```
Robin$ java -jar plovr.jar info
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.plovr.cli.InfoCommand.runCommandWithOptions(InfoCommand.java:25)
	at org.plovr.cli.InfoCommand.runCommandWithOptions(InfoCommand.java:11)
	at org.plovr.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:41)
	at org.plovr.cli.Command.execute(Command.java:47)
	at org.plovr.cli.Main.mainWithExitCode(Main.java:56)
	at org.plovr.cli.Main.main(Main.java:30)
Caused by: java.lang.IllegalArgumentException: resource /revisions/rev-closure-library.txt relative to org.plovr.util.VersionUtil not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
	at com.google.common.io.Resources.getResource(Resources.java:209)
	at org.plovr.util.VersionUtil.readRevisionFromJar(VersionUtil.java:31)
	at org.plovr.util.VersionUtil.<clinit>(VersionUtil.java:23)
	... 6 more
```

**Comment by nicks** [comment]
thanks for the report!

**Comment by nicks** [comment]
should be fixed at HEAD now. it will be fixed in the next release

**Comment by theRobinator** [comment]
Thanks!
