### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by xvilo** [bolinfest/plovr#158]
Hello, 

It seems the unit tests of `org.plovr.AbstractJsInputTest` are broken. I noticed there isn't a CI that checks these things before merge (maybe something to do). I hope we can fix this ASAP.

Output of `buck test` and `buck test --all`

```
Building: finished in 01:10.0 min (100%) 215/215 jobs, 146 updated
  Total time: 01:16.1 min
Testing: finished in 01:24.7 min (80 PASS/1 FAIL)
RESULTS FOR ALL TESTS
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.AbstractGetHandlerTest
FAIL    <100ms  4 Passed   0 Skipped   1 Failed   org.plovr.AbstractJsInputTest
FAILURE org.plovr.AbstractJsInputTest testGoogModule: Regex should allow variable assignment with goog.require expected:<[example.test.Config]> but was:<[]>
java.lang.AssertionError: Regex should allow variable assignment with goog.require expected:<[example.test.Config]> but was:<[]>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.plovr.AbstractJsInputTest.testGoogModule(AbstractJsInputTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at com.facebook.buck.testrunner.SameThreadFailOnTimeout.lambda$new$0(SameThreadFailOnTimeout.java:41)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

PASS      4.2s  2 Passed   0 Skipped   0 Failed   org.plovr.CoffeeScriptCompilerTest
PASS    <100ms  3 Passed   0 Skipped   0 Failed   org.plovr.CompilationCacheTest
PASS     316ms  1 Passed   0 Skipped   0 Failed   org.plovr.CompilationServerTest
PASS      2.8s  5 Passed   0 Skipped   0 Failed   org.plovr.CompilationTest
PASS      5.1s  2 Passed   0 Skipped   0 Failed   org.plovr.CompileRequestHandlerTest
PASS      2.0s  4 Passed   0 Skipped   0 Failed   org.plovr.ConfigParserTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.ConfigPathTest
PASS    <100ms  5 Passed   0 Skipped   0 Failed   org.plovr.ConfigTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed   org.plovr.DepsJsInputTest
PASS    <100ms  3 Passed   0 Skipped   0 Failed   org.plovr.FileUtilTest
PASS    <100ms  5 Passed   0 Skipped   0 Failed   org.plovr.GsonTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed   org.plovr.InputFileHandlerTest
PASS      3.5s  2 Passed   0 Skipped   0 Failed   org.plovr.IntegrationTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.JsSourceFileTest
PASS      4.3s  3 Passed   0 Skipped   0 Failed   org.plovr.ManifestTest
PASS      9.3s  3 Passed   0 Skipped   0 Failed   org.plovr.ModuleConfigTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.ModulesHandlerTest
PASS     22.6s  1 Passed   0 Skipped   0 Failed   org.plovr.NameCollisionTest
PASS      1.8s  1 Passed   0 Skipped   0 Failed   org.plovr.ResourceReaderTest
PASS    <100ms  3 Passed   0 Skipped   0 Failed   org.plovr.SoyFileOptionsTest
PASS     265ms  2 Passed   0 Skipped   0 Failed   org.plovr.SoyFileTest
PASS     26.6s  2 Passed   0 Skipped   0 Failed   org.plovr.TypeScriptCompilerTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed   org.plovr.i18n.PseudoTranslatorTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.soy.server.RequestHandlerSelectorTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed   org.plovr.soy.server.SoyRequestHandlerTest
PASS    <100ms  6 Passed   0 Skipped   0 Failed   org.plovr.util.GsonUtilTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.util.HttpExchangeUtilTest
PASS    <100ms  8 Passed   0 Skipped   0 Failed   org.plovr.util.PairTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.util.VersionUtilTest
TESTS FAILED: 1 FAILURE
Failed target: //:test
FAIL org.plovr.AbstractJsInputTest
```

**Comment by nicks** [comment]
hmmmm...i was not able to reproduce this problem. all the tests pass for me on both macos and linux. what platform are you on?

agree that we should get a CI, tho i remember having trouble getting buck on ci to work, maybe it will be easier now that all the CIs are on containers

**Comment by rgpower** [comment]
I use this [.travis.yml](https://github.com/rgpower/plovr/blob/master/.travis.yml) in my fork of plovr (I didn't bother with fancy stuff like caching, so it's pretty barebones, but it's a working demo at least):

```yaml
language: java
jdk:
  - oraclejdk8

# Enable container-based architecture.
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - ant

before_install:
  # Limit Ant's and Buck's memory usage to avoid the OOM killer.
  - export ANT_OPTS='-Xmx500m'
  - export BUCK_EXTRA_JAVA_ARGS='-Xmx500m'
  # Set up the BUCK BUILD environment.
  - git clone https://github.com/facebook/buck.git $HOME/buck
  - ant -f $HOME/buck/build.xml
  - export PATH=$HOME/buck/bin:$PATH

script:
  - buck clean 2>/dev/null
  - buck fetch ... 2>/dev/null
  - buck test --all 2>/dev/null
```

HTH,
Rick

**Comment by xvilo** [comment]
@nicks We have a clone in our gitlab with gitlab CI. It runs 'linux' where i first noticed it, I have tried running buck on my local mac but that didn't yield any results, so I created a debian VM and tried again. The above output is from the debian 9 vm!

**Comment by xvilo** [comment]
Was also not able to reproduce, will close this
