### ISSUE TITLE
Jar and Tests of v4.1.1 are corrupt

### ISSUE THREAD

**Issue by maximilianvoss** [bolinfest/plovr#73]
Hi,  
downloading the current Master branch (v4.1.1 release) and building the package with ./build-package.sh creates a jar which is not usable. Running this jar leads to an error somewhere around org.plovr.ResourceReader. Looks like some dependencies won't be put into the jar.
 
This can also be seen in your tests running bulk test:

````
FAILURE org.plovr.ResourceReaderTest testClosureLibrarySources: resource /closure/goog/a11y/aria/announcer_test.js relative to org.plovr.ResourceReader not found.
java.lang.IllegalArgumentException: resource /closure/goog/a11y/aria/announcer_test.js relative to org.plovr.ResourceReader not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.common.io.Resources.getResource(Resources.java:209)
	at org.plovr.ResourceJsInput.getCodeWithEtag(ResourceJsInput.java:38)
	at org.plovr.ResourceJsInput.generateCode(ResourceJsInput.java:56)
	at org.plovr.AbstractJsInput.cacheExpensiveValuesIfNecessary(AbstractJsInput.java:126)
	at org.plovr.AbstractJsInput.getCode(AbstractJsInput.java:51)
	at org.plovr.ResourceReaderTest.testClosureLibrarySources(ResourceReaderTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at com.facebook.buck.junit.SameThreadFailOnTimeout$1.call(SameThreadFailOnTimeout.java:45)
	at com.facebook.buck.junit.SameThreadFailOnTimeout$1.call(SameThreadFailOnTimeout.java:41)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by nicks** [comment]
hmmm...not sure how that happened. Thanks for the report! fixed in #74
