### ISSUE TITLE
buck test broken

### ISSUE THREAD

**Issue by joeltine** [bolinfest/plovr#94]
Per the readme, the tests are ran with `buck test`. This command fails with: 

```
>buck test
[-] PROCESSING BUCK FILES...FINISHED 0.0s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.2s [100%] (42/68 JOBS, 0 UPDATED, 0.0% CACHE MISS)
[+] TESTING...0.0s
 |=> //:test...  0.0s (running junit[0.0s])
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/facebook/buck/jvm/java/runner/FileClassPathRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
RESULTS FOR ALL TESTS
FAIL    <100ms  0 Passed   0 Skipped   1 Failed   //:test
FAILURE //:test main: //:test failed with exit code 1:
junit
com.facebook.buck.step.StepFailedException: //:test failed with exit code 1:
junit
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:57)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:71)
	at com.facebook.buck.step.DefaultStepRunner$1.call(DefaultStepRunner.java:92)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

====STANDARD OUT====

====STANDARD ERR====

TESTS FAILED: 1 FAILURE
Failed target: //:test
FAIL //:test
```

Buck version: `buck version 1e5be3e871db3c996e73ac7d9745ce04d0741036`
Plovr was pulled from head

**Comment by nicks** [comment]
this is java's way of telling you that you screwed something up with JDK versions.

**Comment by nicks** [comment]
my guess is that your environment is screwed up so that you're compiling things with java8, then trying to run them on java7

**Comment by joeltine** [comment]
Ya *shrug*. I'm using the google-internal version of java and haven't configured anything myself. At any rate, it's not super important the tests runs as I was able to build plovr fine. Thanks, Nick.
